version: '3.8'


services:
  app:
    build: .
    ports:
      - "8000:82"
    env_file: .env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
        - action: rebuild
          path: main.py