version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:81"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "81", "--reload"]