# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /surya

# Copy the current directory contents into the container at /app
COPY . /surya

COPY .env /surya/.env

# Install dependencies
RUN pip install -r requirements.txt

# Define the command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "81", "--reload"]
